apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zookeeper-operator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: zookeeper-operator
    spec:
      nodeSelector:
          service: zookeeper
      containers:
      - name: zookeeper-operator
        #image: blafrisch/zookeeper-operator:latest
        image: 046982714647.dkr.ecr.us-east-1.amazonaws.com/wirelessregistry/zookeeper-operator:latest
        imagePullPolicy: Always
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
